# Use root as user credentials
version: "3.1"

services:
  mysql:
    image: mysql:8.0.23
    restart: always
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: aamysql2024
      TZ: Asia/Seoul
    ports:
      - 3306:3306
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --log_bin_trust_function_creators=1 --lower_case_table_names=1  --default-time-zone="+09:00"
