apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort
  selector:
    app: sample-app
  ports:
    - protocol: TCP
      port: 80   # cluster 내부에서 사용할 포트
      targetPort: 8080   # pod에서 오픈한 포트